### ISSUE TITLE
Integration with PlantUML Standard Library

### ISSUE THREAD

**Issue by arnaudroques** [michiel/plantuml-kubernetes-sprites#1]
Not really an issue.
Would you mind if we integrate your library to the PlantUML Standard Library ?
(see http://plantuml.com/stdlib )
This would be useful for users.
Thanks!

**Comment by michiel** [comment]
Hi @arnaudroques no problem, go for it. Do you need any other action from me?

**Comment by arnaudroques** [comment]
No other action from you!
We'll post a message here when the integration will be done.
Thanks!

**Comment by arnaudroques** [comment]
Ok, we've just published V1.2019.12 with your library ( http://plantuml.com/stdlib )
The only change we have to do was in file naming : we use `.puml` instead of `.uml`

Thanks again for your contribution !

**Comment by michiel** [comment]
Looks good, thanks @arnaudroques
